name: PRIVATE Build and Push Docker Image To AWS ECR

on:
  workflow_dispatch

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Make application-prod.properties
      run: |
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./application.properties
      shell: bash
      
    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true --file pom.xml
      
    - name: Naming jar file
      run: mv ./target/*.jar ./target/app.jar

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR Private
      id: login-ecr-private
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: private

    - name: Build, tag, and push docker image to Amazon ECR Private
      env:
        REGISTRY: ${{ secrets.ECR_PRIVATE_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com
        REGISTRY_ALIAS: ${{ secrets.ECR_PRIVATE_ID }}
        REPOSITORY: app-with-ecs
        IMAGE_TAG: latest
      run: |
        docker build -t app-with-ecs .
        docker tag app-with-ecs:latest ${{ secrets.ECR_PRIVATE_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/app-with-ecs:latest
        docker push ${{ secrets.ECR_PRIVATE_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/app-with-ecs:latest
